name: Deploy

on:
  push:
    branches: [ 'main' ]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      
    - name: Show request data
      run: |
       echo "Data: ${{ secrets.API_DATA }}"
      
    - name: Check if URL is reachable
      run: curl -v https://a20c657b8f42246639f6b06fff6ee64e-ebe8f97aeec0dd3f.elb.us-west-1.amazonaws.com

    - name: Refresh tags and categories for the Solodit
      id: refreshRequest
      uses: fjogeleit/http-request-action@v1
      with:
        url: https://a20c657b8f42246639f6b06fff6ee64e-ebe8f97aeec0dd3f.elb.us-west-1.amazonaws.com/api/general/refresh_tag_category/
        method: POST
        customHeaders: '{"Content-Type": "application/x-www-form-urlencoded"}'
        data: '{"email": "wang@cyfrin.io", "password": "admin123"}'
    - name: Show Response of Refreshing Tags and Categories
      run: |
        echo ${{ secrets.SOLODIT_USER }}
        echo ${{ secrets.SOLODIT_PASSWORD }}
        echo ${{ steps.refreshRequest.outputs.response }}
    - name: Refresh protocol fork information
      id: refreshForkInfoRequest
      uses: fjogeleit/http-request-action@v1.14.0
      with:
        url: https://a20c657b8f42246639f6b06fff6ee64e-ebe8f97aeec0dd3f.elb.us-west-1.amazonaws.com/api/general/refresh_forked_protocol/
        method: POST
        customHeaders: '{"Content-Type": "application/x-www-form-urlencoded"}'
        data: '{"email": "${{ secrets.SOLODIT_USER }}", "password": "${{ secrets.SOLODIT_PASSWORD }}"}'
    - name: Show Response of Refreshing Protocol Fork Informations
      run: |
        echo ${{ steps.refreshForkInfoRequest.outputs.response }}
        echo ${{ steps.myRequest.outputs.headers }}
    - name: Import reports
      id: importReportRequest
      uses: fjogeleit/http-request-action@v1.14.0
      with:
        url: https://a20c657b8f42246639f6b06fff6ee64e-ebe8f97aeec0dd3f.elb.us-west-1.amazonaws.com/api/general/import_reports/
        method: POST
        customHeaders: '{"Content-Type": "application/x-www-form-urlencoded"}'
        data: '{"email": "${{ secrets.SOLODIT_USER }}", "password": "${{ secrets.SOLODIT_PASSWORD }}"}'
    - name: Show Response of Importing Reports
      run: |
        echo ${{ steps.importReportRequest.outputs.response }}
        echo ${{ steps.myRequest.outputs.headers }}
    - name: Refresh bug bounties
      id: refreshBugBounties
      uses: fjogeleit/http-request-action@v1.14.0
      with:
        url: https://a20c657b8f42246639f6b06fff6ee64e-ebe8f97aeec0dd3f.elb.us-west-1.amazonaws.com/api/general/refresh_bug_bounties/
        method: POST
        customHeaders: '{"Content-Type": "application/x-www-form-urlencoded"}'
        data: '{"email": "${{ secrets.SOLODIT_USER }}", "password": "${{ secrets.SOLODIT_PASSWORD }}"}'
    - name: Show Response of Refreshing Bug bounties
      run: |
        echo ${{ steps.refreshBugBounties.outputs.response }}
        echo ${{ steps.myRequest.outputs.headers }}
